### ISSUE TITLE
Plugin Upgrade to v2024

### ISSUE THREAD

**Issue by ebukaracer** [nadia-tarashkevich/ClearRecentProjectsList#1]
I've been using the plugin, and it has been working nicely and as expected. 

Please, can you upgrade it to support version 2024+?

Also, if there is a way to add the menu to JetBrains' tool welcome screen, that would be very handy! I'm using RIDER in this case.

**Comment by nadia-tarashkevich** [comment]
I updated to 2024.1 
Please ping me on 2024.2, it would be one more update
